### PR TITLE
Migrate to ZIO 2.0.0-RC6

### PR DESCRIPTION
**Pull request by ghostdogpr**

### CODE REVIEW

**Comment by regis-leray** [comment]
Thank you @ghostdogpr, i started a branch locally but i never completed.
need to investigate why unit test are failing...

**Comment by regis-leray** [comment]
weird i run the tests on my local machine and i dont have any issues :(

**Comment by ghostdogpr** [comment]
@regis-leray it looks like minio had internal changes and the things that worked before are not working with the latest minio image. I almost fixed all, will fix the last one now.

**Comment by regis-leray** [comment]
Thank you so much !

**Comment by ghostdogpr** [comment]
Do you mind releasing it?

**Comment by regis-leray** [comment]
voila 
https://github.com/zio/zio-s3/releases/tag/v0.4.0-RC6 :)

**Pull request merged**
